# Generated by Django 3.0.5 on 2020-08-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='profile_1',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='profile_2',
        ),
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='savedmessageschat',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='savedmessagesmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='savedmessagesmessage',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
        migrations.DeleteModel(
            name='GroupChatMessage',
        ),
        migrations.DeleteModel(
            name='PrivateChat',
        ),
        migrations.DeleteModel(
            name='PrivateChatMessage',
        ),
        migrations.DeleteModel(
            name='SavedMessagesChat',
        ),
        migrations.DeleteModel(
            name='SavedMessagesMessage',
        ),
    ]
