# Generated by Django 3.0.5 on 2020-08-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0003_chat_groupchat_groupchatmessage_privatechat_privatechatmessage_savedmessageschat_savedmessagesmessag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(default='', upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='image',
            field=models.ImageField(default='', upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='savedmessageschat',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='savedmessageschat',
            name='image',
            field=models.ImageField(default='', upload_to='assets'),
        ),
    ]
