# Generated by Django 3.0.5 on 2020-08-26 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0005_auto_20200826_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='CommonChat',
        ),
        migrations.RenameField(
            model_name='groupchat',
            old_name='chat',
            new_name='common_chat',
        ),
        migrations.RenameField(
            model_name='privatechat',
            old_name='chat',
            new_name='common_chat',
        ),
        migrations.RenameField(
            model_name='savedmessageschat',
            old_name='chat',
            new_name='common_chat',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='name',
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chating.GroupChat'),
        ),
        migrations.AlterField(
            model_name='privatechatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chating.PrivateChat'),
        ),
        migrations.AlterField(
            model_name='savedmessagesmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chating.SavedMessagesChat'),
        ),
    ]
