# Generated by Django 3.0.5 on 2020-08-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0002_profile_status'),
        ('chating', '0006_auto_20200827_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedMessagesMessage',
            new_name='ChatMessage',
        ),
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='profile',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chating.CommonChat'),
        ),
        migrations.DeleteModel(
            name='GroupChatMessage',
        ),
        migrations.DeleteModel(
            name='PrivateChatMessage',
        ),
    ]
