# Generated by Django 3.0.5 on 2020-08-24 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('OT', 'other')], max_length=2)),
                ('main_quote', models.CharField(default='', max_length=254)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('profession', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='assets')),
                ('relationships', models.ManyToManyField(related_name='related_to', through='relationship.Relationship', to='users_profile.Profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
